version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: tg_web_dev
    container_name: tg_web_dev
    command: /start-django
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    expose:
      - 9010
    ports:
      - 9010:9010
    env_file:
      - ./.env/.dev.env
    depends_on:
      - db
      - redis

  tg_bot:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: tg_bot
    container_name: tg_bot
    command: /start-bot
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.3
    container_name: debts_info_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "debts_info_bot"
      POSTGRES_PASSWORD: "debts_info_bot"
      POSTGRES_DB: "debts_info_bot_dev"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U debts_info_bot -d debts_info_bot_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: tg_redis
    volumes:
      - redis-data:/data

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: tg_celeryworker
    container_name: tg_celeryworker
    command: /start-worker
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: tg_celerybeat
    container_name: tg_celerybeat
    command: /start-beat
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev.env
    depends_on:
      - redis
      - db

volumes:
  redis-data:
  postgres_data:
