# Generated by Django 4.1.7 on 2023-03-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя кредитора')),
            ],
            options={
                'verbose_name': 'Кредитор',
                'verbose_name_plural': 'Кредитор',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма кредита/займа')),
                ('bet', models.IntegerField(verbose_name='% Ставка в год')),
                ('register_date', models.DateTimeField(verbose_name='Дата оформления')),
                ('return_date', models.DateTimeField(verbose_name='Дата возврата')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.creditor', verbose_name='Кредитор')),
            ],
            options={
                'verbose_name': 'Кредит/Займ',
                'verbose_name_plural': 'Кредиты/Займы',
            },
        ),
    ]
