# Generated by Django 4.1.7 on 2023-03-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_creditor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='comment',
            field=models.TextField(default=None, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
