# Generated by Django 4.1.7 on 2023-03-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_credit_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Сумма на текущий день'),
        ),
    ]
